baseURL = '/'
languageCode = 'en-us'
title = "ImNoob"
theme = "mainroad"

[pagination]
  pagerSize = 5

[Params]
  description = "ImNoob's Personal blog about everything"
  dateFormat = "02 January 2006"
  opengraph = true
  twitter_cards = true
  readmore = true 
  showAuthor = true
  showComments = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["posts", "docs","categories"]
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[params]
favicon = "img/nooblogo.png"

[Params.Author]
  name = "ImNoob"
  bio = "ImNoob's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params.logo]
  subtitle = "Proudly clueless, constantly learning!"
  image = "img/nooblogo.png"

[Params.style.vars]
  highlightColor = "#e22d30"
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.thumbnail]
  visibility = ["list", "post"]
  
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  twitter = "yohjawa"
  instagram = "yohjawa"
  linkedin = "yohjawa"
  telegram = "imnoob"
  github = "yohja"
  email = "me@imnoob.net"

[Params.widgets.search]
  cached = false # activate cache if true
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""

[Params.remark42]
  enabled = true
  host ="https://comments.imnoob.net"
  site = "comments.imnoob.net"
  locale = "en"